[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sauna"
authors = [{name = "Alexander Ryzhkov", email = "Alexander_Ryzhkov@outlook.com"}]
description = "SAUNA: A Python package for sensitivity and uncertainty analysis"
license = {file = "LICENSE"}
dynamic = ["version", "readme"]
requires-python = ">=3.8"
keywords = ["sauna", "sensitivity", "uncertainty", "nuclear data", "target accuracy requirements",
            "similarity assessment", "uncertainty quantification"]
classifiers=[
             "Development Status :: 4 - Beta",
             "Intended Audience :: Developers",
             "Intended Audience :: Science/Research",
             "Intended Audience :: End Users/Desktop",
             "Topic :: Scientific/Engineering",  
             "License :: OSI Approved :: MIT License",  
             "Natural Language :: English",
             "Operating System :: Unix",        
             "Programming Language :: Python :: 3",
             "Programming Language :: Python :: 3.8",
            ]

dependencies = ["sandy", "serpentTools", "numpy", "scipy", "pandas", "matplotlib"]

[project.optional-dependencies]
docs = ["jupyter"]

[tool.setuptools.packages.find]
include = ["sauna*"]

[tool.setuptools.dynamic]
version = {attr = "sauna.__version__"}
readme = {file = "README.md"}

[project.urls]
Homepage = "https://sauna-dev.gitbook.io"
Documentation = "https://sauna-dev.gitbook.io"
Repository = "https://github.com/AARyzhkov/sauna.git"
Issues = "https://github.com/AARyzhkov/sauna/issues"